<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" total="5" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="87427" started-at="2015-06-08T00:39:23Z" finished-at="2015-06-08T00:40:50Z">
    <groups>
      <group name="a">
        <method signature="TestGoogleSearch.testLogin()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testLogin" class="com.learn.TestGoogleSearch"/>
      </group> <!-- a -->
      <group name="b">
        <method signature="TestGoogleSearch.testProfile()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testProfile" class="com.learn.TestGoogleSearch"/>
      </group> <!-- b -->
      <group name="c">
        <method signature="TestGoogleSearch.testReportUTI()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testReportUTI" class="com.learn.TestGoogleSearch"/>
      </group> <!-- c -->
      <group name="d">
        <method signature="TestGoogleSearch.testCases()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testCases" class="com.learn.TestGoogleSearch"/>
      </group> <!-- d -->
      <group name="e">
        <method signature="TestGoogleSearch.testLogOut()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testLogOut" class="com.learn.TestGoogleSearch"/>
      </group> <!-- e -->
    </groups>
    <test name="Default test" duration-ms="87427" started-at="2015-06-08T00:39:23Z" finished-at="2015-06-08T00:40:50Z">
      <class name="com.learn.TestGoogleSearch">
        <test-method status="PASS" signature="beforeTest()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="beforeTest" is-config="true" duration-ms="12265" started-at="2015-06-07T19:39:23Z" finished-at="2015-06-07T19:39:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeTest -->
        <test-method status="PASS" signature="testLogin()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testLogin" duration-ms="25734" started-at="2015-06-07T19:39:35Z" finished-at="2015-06-07T19:40:01Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogin -->
        <test-method status="FAIL" signature="testProfile()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testProfile" duration-ms="49406" depends-on-groups="a" started-at="2015-06-07T19:40:01Z" finished-at="2015-06-07T19:40:50Z">
          <exception class="org.openqa.selenium.remote.UnreachableBrowserException">
            <message>
              <![CDATA[Error communicating with the remote browser. It may have died.
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:17:10'
System info: host: 'dhcp-10-105-106-210.wireless.northwestern.private', ip: '10.105.106.210', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_45'
Driver info: driver.version: AppiumDriver]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.openqa.selenium.remote.UnreachableBrowserException: Error communicating with the remote browser. It may have died.
Build info: version: '2.46.0', revision: '87c69e2', time: '2015-06-04 16:17:10'
System info: host: 'dhcp-10-105-106-210.wireless.northwestern.private', ip: '10.105.106.210', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.10.2', java.version: '1.8.0_45'
Driver info: driver.version: AppiumDriver
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:599)
	at io.appium.java_client.AppiumDriver.execute(AppiumDriver.java:180)
	at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:269)
	at org.openqa.selenium.remote.RemoteWebElement.click(RemoteWebElement.java:80)
	at com.learn.TestGoogleSearch.testProfile(TestGoogleSearch.java:87)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:663)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:849)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1157)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.apache.http.conn.HttpHostConnectException: Connect to 127.0.0.1:4723 [/127.0.0.1] failed: Connection refused
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:151)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:353)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:380)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:184)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:88)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:71)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:55)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.fallBackExecute(ApacheHttpClient.java:161)
	at org.openqa.selenium.remote.internal.ApacheHttpClient.execute(ApacheHttpClient.java:89)
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:134)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:578)
	... 28 more
Caused by: java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:74)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:134)
	... 41 more
]]>
            </full-stacktrace>
          </exception> <!-- org.openqa.selenium.remote.UnreachableBrowserException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testProfile -->
        <test-method status="SKIP" signature="testReportUTI()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testReportUTI" duration-ms="0" depends-on-groups="b" started-at="2015-06-07T19:40:50Z" finished-at="2015-06-07T19:40:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestGoogleSearch.testReportUTI()[pri:0, instance:com.learn.TestGoogleSearch@7d417077] depends on not successfully finished methods in group "b"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestGoogleSearch.testReportUTI()[pri:0, instance:com.learn.TestGoogleSearch@7d417077] depends on not successfully finished methods in group "b"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testReportUTI -->
        <test-method status="SKIP" signature="testCases()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testCases" duration-ms="0" depends-on-groups="c" started-at="2015-06-07T19:40:50Z" finished-at="2015-06-07T19:40:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestGoogleSearch.testCases()[pri:0, instance:com.learn.TestGoogleSearch@7d417077] depends on not successfully finished methods in group "c"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestGoogleSearch.testCases()[pri:0, instance:com.learn.TestGoogleSearch@7d417077] depends on not successfully finished methods in group "c"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testCases -->
        <test-method status="SKIP" signature="testLogOut()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="testLogOut" duration-ms="0" depends-on-groups="d" started-at="2015-06-07T19:40:50Z" finished-at="2015-06-07T19:40:50Z">
          <exception class="java.lang.Throwable">
            <message>
              <![CDATA[Method TestGoogleSearch.testLogOut()[pri:0, instance:com.learn.TestGoogleSearch@7d417077] depends on not successfully finished methods in group "d"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.Throwable: Method TestGoogleSearch.testLogOut()[pri:0, instance:com.learn.TestGoogleSearch@7d417077] depends on not successfully finished methods in group "d"
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1067)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:771)
	at org.testng.TestRunner.run(TestRunner.java:621)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1200)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1125)
	at org.testng.TestNG.run(TestNG.java:1033)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.Throwable -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testLogOut -->
        <test-method status="PASS" signature="afterTest()[pri:0, instance:com.learn.TestGoogleSearch@7d417077]" name="afterTest" is-config="true" duration-ms="0" started-at="2015-06-07T19:40:50Z" finished-at="2015-06-07T19:40:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- com.learn.TestGoogleSearch -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
